// Create a function to change
// the hash value of the page
$("switch-lang-it").hide();

function switchLanguage(lang) {
    location.hash = lang;
    location.reload();
    }

    // Define the language reload anchors
    var language = {
    it: {
        hi: "Ciao!",
        wewantyou: "Vogliamo farti giocare alla Realtà Virtuale in maniera completamente gratuita.",
        findoutmore: "Scopri di più",

        whoarewe: "Cosa siamo?",
        whoarewe_context: "Siamo un’<b>associazione no-profit</b> che organizza eventi a <b>Trento</b> in cui si gioca ai nostri visori per la Realtà Virtuale, il tutto <b>completamente gratuito</b>.",

        whatkindofevents: "Che tipo di eventi?",
        whatkindofevents_context: "Miriamo a un <b>appuntamento settimanale</b>, solitamente verso la sera, idealmente in un bar, dove <b>a turni facciamo giocare</b> delle esperienze in Realtà Virtuale con un <b>Meta Quest 2</b>.<br><br>Non serve alcun tipo di prenotazione, basta presentarsi e giocare!",

        dalle_example: "Un esempio di come sono i nostri eventi. Immagine generata da DALL-E 2, un'intelligenza artificiale, con la seguente frase: <i>\"A group of people in a bar staring at one person wearing a VR headset, painting style\"</i>",

        whatkindofexperiences: "Che tipo di esperienze?",
        whatkindofexperiences_context_one: "Al momento queste sono le esperienze che facciamo provare:",
        whatkindofexperiences_context_two: "Teniamo questa lista sempre aggiornata e annunceremo ogni aggiunta su tutti i nostri social.<br><br>Se non sai cosa giocare, non ti preoccupare! Ti consigliamo noi 😊",

        interested: "Interessatǝ?",
        calltoaction: "Seguici sui nostri social per restare aggiornatǝ sui nostri eventi!",
        socialmedias: "Tutti i nostri social",

        businessmodel: "Ma come guadagnate?",
        businessmodel_context: "<b>Non vogliamo guadagnare!</b> Il nostro scopo è puramente quello di <b>far conoscere alla gente la potenzialità della Realtà Virtuale</b> come il <b>mezzo di intrattenimento del futuro</b>, e farla divertire allo stesso tempo!<br><br>Abbiamo solo un box donazioni: tutte le offerte vanno alla manutenzione del visore e Save the Children Italia.",
    
        collaboration: "Collaborazioni",
        collaboration_context: "Vuoi partecipare al progetto o collaborare con noi? Scrivi un'email a <b><a href=\"mailto:hey@trentovrsociety.it\">hey@trentovrsociety.it</a></b>!"
    },
    en: {
        hi: "Hi!",
        wewantyou: "We want you to play Virtual Reality for free.",
        findoutmore: "Find out more",

        whoarewe: "Who are we?",
        whoarewe_context: "We're a <b>no-profit organization</b> that plans events in <b>Trento</b> where people can come and play with our Virtual Reality headsets. All of it <b>for free</b>.",

        whatkindofevents: "What kind of events?",
        whatkindofevents_context: "We currently aim to have a <b>weekly event</b>, around evening, ideally in a pub, where <b>people play experiences in turns</b> with our Meta Quest 2.<br><br>No kind of reservation needed, just come and play!",

        dalle_example: "An example of how our events are supposed to look like. This picture was generated by DALL-E 2, an AI, with the following prompt: <i>\"A group of people in a bar staring at one person wearing a VR headset, painting style\"</i>",

        whatkindofexperiences: "What experiences?",
        whatkindofexperiences_context_one: "Currently, these are the experiences that we offer:",
        whatkindofexperiences_context_two: "We keep this list updated and will announce every addition on all our social medias.<br><br>If you don't know what to play exactly, no worries! We'll give you some ideas 😊",

        interested: "Interested?",
        calltoaction: "Follow us on our social medias to stay up to date with our events!",
        socialmedias: "Our social medias",

        businessmodel: "So how do you exactly make money?",
        businessmodel_context: "<b>We don't!</b> We only want <b>people to know about Virtual Reality's potential</b> to be <b>the entertainment of the future</b>, and make them have fun at the same time!<br><br>All we have is a donation box: every donation will go towards the headset's maintenance and Save the Children Italia.",

        collaboration: "Collaboration",
        collaboration_context: "Looking to join the project or collaborate with us? Contact us at <b><a href=\"mailto:hey@trentovrsociety.it\">hey@trentovrsociety.it</a></b>"
    },
    };

    // Check if a hash value exists in the URL
    if (window.location.hash) {

    // Set the content of the webpage 
    // depending on the hash value
    if (window.location.hash == "#it") {
        $("#switch-lang-it").hide();

        lang_hi.innerHTML = language.it.hi;
        lang_wewantyou.innerHTML = language.it.wewantyou;
        lang_findoutmore.innerHTML = language.it.findoutmore;

        lang_whoarewe.innerHTML = language.it.whoarewe;
        lang_whoarewe_context.innerHTML = language.it.whoarewe_context;

        lang_whatkindofevents.innerHTML = language.it.whatkindofevents;
        lang_whatkindofevents_context.innerHTML = language.it.whatkindofevents_context;

        lang_dalle_example.innerHTML = language.it.dalle_example;

        lang_whatkindofexperiences.innerHTML = language.it.whatkindofexperiences;
        lang_whatkindofexperiences_context_one.innerHTML = language.it.whatkindofexperiences_context_one;
        lang_whatkindofexperiences_context_two.innerHTML = language.it.whatkindofexperiences_context_two;

        lang_interested.innerHTML = language.it.interested;
        lang_calltoaction.innerHTML = language.it.calltoaction;
        lang_socialmedias.innerHTML = language.it.socialmedias;

        lang_businessmodel.innerHTML = language.it.businessmodel;
        lang_businessmodel_context.innerHTML = language.it.businessmodel_context;

        lang_collaboration.innerHTML = language.it.collaboration;
        lang_collaboration_context.innerHTML = language.it.collaboration_context;
    }
    else if (window.location.hash == "#en") {
        $("#switch-lang-en").hide();

        lang_hi.innerHTML = language.en.hi;
        lang_wewantyou.innerHTML = language.en.wewantyou;
        lang_findoutmore.innerHTML = language.en.findoutmore;

        lang_whoarewe.innerHTML = language.en.whoarewe;
        lang_whoarewe_context.innerHTML = language.en.whoarewe_context;

        lang_whatkindofevents.innerHTML = language.en.whatkindofevents;
        lang_whatkindofevents_context.innerHTML = language.en.whatkindofevents_context;

        lang_dalle_example.innerHTML = language.en.dalle_example;

        lang_whatkindofexperiences.innerHTML = language.en.whatkindofexperiences;
        lang_whatkindofexperiences_context_one.innerHTML = language.en.whatkindofexperiences_context_one;
        lang_whatkindofexperiences_context_two.innerHTML = language.en.whatkindofexperiences_context_two;

        lang_interested.innerHTML = language.en.interested;
        lang_calltoaction.innerHTML = language.en.calltoaction;
        lang_socialmedias.innerHTML = language.en.socialmedias;

        lang_businessmodel.innerHTML = language.en.businessmodel;
        lang_businessmodel_context.innerHTML = language.en.businessmodel_context;

        lang_collaboration.innerHTML = language.en.collaboration;
        lang_collaboration_context.innerHTML = language.en.collaboration_context;
    }
    } else {
        $("#switch-lang-it").hide();
    }